server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
      base-path: /myactuator
  endpoint:
    shutdown:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
logging:
  level:
    com:
      zensar:
        springbootdemo: debug
